

all:
	make -C randstones
	make -C window
	make -C line
	make -C morph
	make -C grid
	make -C pack
	make -C merge
	make -C find2
	make -C 3dtosvg
	
clean:
	rm -f */*.out.svg */*.out.png
	make -C 3dtosvg clean
	
	