

all: dong paper
dong:
	sh ../test.sh ../../extensions/speleo_morph.py "" dong
paper:
	sh ../test.sh ../../extensions/speleo_morph.py "" paper

paper2:
	sh ../test.sh ../../extensions/speleo_morph.py "--rotate-symbols=true" paper2
	