
unstyled:
	cat cave_symbols.svg  | sed 's/id="/id="gr/g;s/>Cave plan</>Cave plan - Unstyled</;s/#000000/inherit/g;s/xlink:href="#/xlink:href="#gr/g;s/stroke-width:[0-9.]\+\(;\|"\)/stroke-width:inherit\1/' > cave_symbols_unstyled.svg
	cat cave_rocks.svg  | sed 's/id="/id="un/g;s/>Cave rocks</>Cave rocks - Unstyled</;s/\(#000000\|none\)/inherit/g;s/xlink:href="#/xlink:href="#un/g;s/stroke-width:[0-9.]\+\(;\|"\)/stroke-width:inherit\1/' > cave_rocks_unstyled.svg
	