all:
	sh ../test.sh ../../extensions/speleo_pack.py "--mode=pack" window_pack
	sh ../test.sh ../../extensions/speleo_pack.py "--mode=unpack --id=source " window_unpack
	sh ../test.sh ../../extensions/speleo_pack.py "--mode=unpack --id=packed " hard_unpack
	sh ../test.sh ../../extensions/speleo_pack.py "--mode=unpack --id=packed " harder_unpack
